### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [florimondmanca/uptv#7]
Hello, @florimondmanca 

I contribute to open source softwares by designing logos. I realized that the uptv doesn't have a logo. How is the logo? I will wait for feedback...

![1](https://user-images.githubusercontent.com/36298335/46864899-51200e80-ce24-11e8-9915-4a5da12b9108.jpg)

**Comment by florimondmanca** [comment]
Hi @reallinfo ,

Thanks for offering! :+1: Very kind of you.
We already have an unofficial logo which we just haven't uploaded to the repo/project yet.

I'm closing this issue. Thanks again and have a great day!
